### ISSUE TITLE
Not compatible with PHP 7.2

### ISSUE THREAD

**Issue by jens1o** [Microsoft/tolerant-php-parser#163]
because it uses count without checking whether it is compatible with php 7.2

```
[Error - 3:11:03 PM] Error parsing file:///c:/nginx/html/projects/WCF/wcfsetup/install/files/lib/data/core/object/CoreObjectList.class.php: ErrorException: count(): Parameter must be an array or an object that implements Countable in C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\microsoft\tolerant-php-parser\src\PhpTokenizer.php:78
Stack trace:
#0 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\microsoft\tolerant-php-parser\src\PhpTokenizer.php(78): {closure}(2, 'count(): Parame...', 'C:\\Users\\Jens\\....', 78, Array)
#1 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\microsoft\tolerant-php-parser\src\Node.php(433): Microsoft\PhpParser\PhpTokenizer::getTokensArrayFromContent('<?php \n\n/**\n * ...', 0, 70, false)
#2 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\src\DefinitionResolver.php(139): Microsoft\PhpParser\Node->getDocCommentText()
#3 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\src\DefinitionResolver.php(115): LanguageServer\DefinitionResolver->getDocBlock(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#4 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\src\DefinitionResolver.php(234): LanguageServer\DefinitionResolver->getDocumentationFromNode(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#5 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(105): LanguageServer\DefinitionResolver->createDefinitionFromNode(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration), 'wcf\\data\\core\\o...')
#6 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(67): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#7 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(52): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\SourceFileNode))
#8 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\src\PhpDocument.php(147): LanguageServer\TreeAnalyzer->__construct(Object(Microsoft\PhpParser\Parser), '<?php\nnamespace...', Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver), 'file:///c:/ngin...')
#9 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\src\PhpDocument.php(105): LanguageServer\PhpDocument->updateContent('<?php\nnamespace...')
#10 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(141): LanguageServer\PhpDocument->__construct('file:///c:/ngin...', '<?php\nnamespace...', Object(LanguageServer\Index\Index), Object(Microsoft\PhpParser\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#11 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(120): LanguageServer\PhpDocumentLoader->create('file:///c:/ngin...', '<?php\nnamespace...')
#12 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#13 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\sabre\event\lib\coroutine.php(70): Generator->send('<?php\nnamespace...')
#14 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}('<?php\nnamespace...')
#15 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#16 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#17 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#18 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#19 C:\Users\Jens\.vscode-insiders\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#20 {main}
```

// cc @felixfbecker

**Comment by felixfbecker** [comment]
I don't see `count` being used at that line. This was fixed in bb15f005
https://sourcegraph.com/github.com/Microsoft/tolerant-php-parser/-/blob/src/PhpTokenizer.php#L78-79

**Comment by jens1o** [comment]
Ah, okay, when do you update these dependencies? I want to use php 7.2 beta as of now, to report bugs.

**Comment by felixfbecker** [comment]
When @roblourens cuts a new release

**Comment by roblourens** [comment]
I just pushed v0.0.4 with that commit :)

**Comment by jens1o** [comment]
Thank you @roblourens !
